### ISSUE TITLE
Eden's Verse Refulgence has wrong content

### ISSUE THREAD

**Issue by Fyrhtu** [Aho-Senpai/Aho-Senpai#1]
It appears that the Aho's Raids, Raids, 8-Main Raids, 5.0 - Shadowbringers, 08 - Eden's Verse: Refulgence, E8S (From @Forgotten Freedom) has the wrong content; looks like another instance/raid folder got copied over.

**Comment by Aho-Senpai** [comment]
Wrong repository. see : https://github.com/Aho-Senpai/Aho-Triggers
